DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE EMPLOYEES (
   id INT AUTO_INCREMENT  PRIMARY KEY,
   name VARCHAR(250) NOT NULL,
   age INT NOT NULL,
   email VARCHAR(100) NOT NULL,
   position1 VARCHAR(250) NOT NULL,
   timestamp1 VARCHAR(250) NOT NULL
);